# ============================
# DEV Profile - Neon PostgreSQL
# ============================
spring.datasource.url=jdbc:postgresql://ep-dry-snow-a9cjiosn-pooler.gwc.azure.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4zcgvqM8OhJI
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging de SQL en desarrollo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console desactivada (usamos PostgreSQL)
spring.h2.console.enabled=false

# Data SQL desactivado ? la BD se gestiona manualmente con scripts
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false


