# ============================
# PROD Profile - Render + Neon PostgreSQL
# ============================
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ep-dry-snow-a9cjiosn-pooler.gwc.azure.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DATABASE_USER:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD:npg_4zcgvqM8OhJI}
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=false
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

# Logging
spring.jpa.show-sql=false
