# ============================
# WoW Companion - Common Config
# ============================
spring.application.name=WoWCompanion
server.port=${PORT:8084}

# Active profile (dev | prod)
spring.profiles.active=dev

# JPA common
spring.jpa.open-in-view=false

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# Cache
spring.cache.type=simple
